=== EdimBatalla/DAM/DAM_01/Llenguatge de Marques/RA_04_DTD i JSON/Practica_04/Exercici_07.dtd
<!ELEMENT projecte (nom, equips)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT equips (equip+)>
<!ELEMENT equip (nom, membres)>
<!ELEMENT membres (membre+)>
<!ELEMENT membre EMPTY>
<!ATTLIST membre nom CDATA #REQUIRED rol (developer | tester | manager) #REQUIRED>

=== EdimBatalla/DAM/DAM_01/Llenguatge de Marques/RA_04_DTD i JSON/Practica_04/Exercici_07.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE projecte SYSTEM "Exercici_07.dtd">

<projecte>
    <nom>Desenvolupament de Software</nom>
    <equips>
        <equip>
            <nom>Backend</nom>
            <membres>
                <membre nom="Joan" rol="developer"/>
                <membre nom="Maria" rol="manager"/>
            </membres>
        </equip>
        <equip>
            <nom>QA</nom>
            <membres>
                <membre nom="Anna" rol="tester"/>
            </membres>
        </equip>
    </equips>
</projecte>
