=== EdimBatalla/DAM/DAM_01/Llenguatge de Marques/RA_04_DTD i JSON/Practica_04/Exercici_09.dtd
<!ELEMENT empresa (departament+)>
<!ELEMENT departament (empleat+)>
<!ATTLIST departament
    nom CDATA #REQUIRED>
<!ELEMENT empleat (nom, email?)>
<!ATTLIST empleat
    id ID #REQUIRED
    posicio CDATA #REQUIRED>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT email (#PCDATA)>

=== EdimBatalla/DAM/DAM_01/Llenguatge de Marques/RA_04_DTD i JSON/Practica_04/Exercici_09.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE empresa SYSTEM "Exercici_09.dtd">

<empresa>
<departament nom="HR">
<empleat id="e1" posicio="Manager">
<nom>Maria</nom>
<email>maria@empresa.com</email>
</empleat>
</departament>
<departament nom="IT">
<empleat id="e2" posicio="Developer">
<nom>Joan</nom>
</empleat>
</departament>
</empresa>
