=== EdimBatalla/DAM/DAM_01/Llenguatge de Marques/RA_04_DTD i JSON/Practica_04/exercici_01.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE llibreria [
    <!ELEMENT llibreria (llibres, revistes)>
    <!ELEMENT llibres (llibre*)>
    <!ELEMENT llibre EMPTY>
    <!ATTLIST llibre
        titol CDATA #REQUIRED
        autor CDATA #IMPLIED>
    <!ELEMENT revistes (revista*)>
    <!ELEMENT revista EMPTY>
    <!ATTLIST revista
        nom CDATA #REQUIRED
        periodicitat (diari | setmanal | mensual) #IMPLIED>

=== EdimBatalla/DAM/DAM_01/Llenguatge de Marques/RA_04_DTD i JSON/Practica_04/exercici_01.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE llibreria SYSTEM "exercici_01.dtd">
<llibreria>
    <llibres>
        <llibre titol="El Senyor dels Anells" autor="J.R.R. Tolkien"/>
        <llibre titol="1984" autor="George Orwell"/>
        <llibre titol="El Quixot"/>
    </llibres>
    <revistes>
        <revista nom="National Geographic" periodicitat="mensual"/>
        <revista nom="La Vanguardia" periodicitat="diari"/>
        <revista nom="Time" periodicitat="setmanal"/>
    </revistes>
</llibreria>
