=== EdimBatalla/DAM/DAM_01/Llenguatge de Marques/RA_04_DTD i JSON/Practica_04/exercici_02.dtd
<!ELEMENT universitat (estudiant*, professor*)>
<!ELEMENT estudiant (nom, cognom)>
<!ELEMENT professor (nom, cognom)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT cognom (#PCDATA)>

<!ATTLIST professor
    categoria CDATA #REQUIRED>
<!ATTLIST estudiant
    rol (delegat | subdelegat) #IMPLIED>

=== EdimBatalla/DAM/DAM_01/Llenguatge de Marques/RA_04_DTD i JSON/Practica_04/exercici_02.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE universitat PUBLIC "-//EXEMPLE//DTD Universitat//EN" "exercici_02.dtd">

<universitat>
    <estudiant rol="delegat">
        <nom>Joan</nom>
        <cognom>Pérez</cognom>
    </estudiant>
    <estudiant>
        <nom>Maria</nom>
        <cognom>López</cognom>
    </estudiant>
    <professor categoria="Matemàtiques">
        <nom>Anna</nom>
        <cognom>García</cognom>
    </professor>
    <professor categoria="Història">
        <nom>Carles</nom>
        <cognom>Martí</cognom>
    </professor>
</universitat>
