=== EdimBatalla/DAM/DAM_01/Llenguatge de Marques/RA_04_DTD i JSON/Exemples/comanda.dtd
<!ELEMENT comanda (client, articles, total) >
<!ATTLIST comanda numero NMTOKEN #REQUIRED >
<!ATTLIST comanda dia NMTOKEN #REQUIRED>
 
<!ELEMENT client (nom,cognom) >
<!ATTLIST client codi NMTOKEN #IMPLIED >
 
<!ELEMENT total EMPTY>
<!ATTLIST total valor CDATA #REQUIRED >
 
<!ELEMENT articles (article+)>
<!ELEMENT article (descripció, quantitat, preu)>
 
<!ELEMENT nom (#PCDATA)>
<!ELEMENT cognom (#PCDATA)>
<!ELEMENT descripció (#PCDATA)>
<!ELEMENT quantitat (#PCDATA)>
<!ELEMENT preu (#PCDATA)>

=== EdimBatalla/DAM/DAM_01/Llenguatge de Marques/RA_04_DTD i JSON/Exemples/prova1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE comanda SYSTEM "comanda.dtd">
<comanda numero="26" dia="2011-12-01" >
    <client codi="20">
        <nom>Frederic</nom>
        <cognom>Garcia</cognom>
    </client>
    <articles>
        <article>
            <descripci贸>Yoda Mimobot USB Flash Drive 8GB</descripci贸>
            <quantitat>5</quantitat>
            <preu>38.99</preu>
        </article>
        <article>
            <descripci贸>Darth Vader Half Helmet Case for iPhone</descripci贸>
            <quantitat>2</quantitat>
        <preu>29.95</preu>
        </article>
    </articles>
    <total valor="254,85"/>
    <total>254.85</total>
</comanda>
